output:
  formats:
    - format: line-number

linters:
  enable:
    - goimports
    - golint
    - gofmt
    - misspell
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gochecknoinits
    - unconvert
    - unparam
    - exportloopref

run:
  timeout: 2m

issues:
  new-from-rev: "490e245"