version: "2"

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

linters:
  default: all

run:
  timeout: 2m

issues:
  new-from-rev: "490e245"
